version: '3.3'
services:
  database:
    image: mysql:8.0
    container_name: project-db
    command: --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=${DB_NAME:-project_database}
      - MYSQL_USER=${DB_USER:-project}
      - MYSQL_PASSWORD=${DB_PASS:-project123!db}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-project123!db}
      - TZ=${TZ:-Asia/Tokyo}
    volumes:
      # - ./docker/db-data:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT:-3011}:3306
    stdin_open: true
    tty: true
    restart: always
  app:
    container_name: project-app
    build:
      context: ./docker/php/
      args:
        - TZ=${TZ:-Asia/Tokyo}
    ports:
      - ${APP_PORT:-9969}:8000
    volumes:
      - ${SOURCE:-./src}:/work/app:delegated
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/ash:/etc/profile.d
      - ./docker/php/psysh:/root/.config/psysh
      - ./docker/php/supervisord.conf:/etc/supervisord.conf
      - ./docker/php/supervisord.d:/etc/supervisord.d
    working_dir: /work/app
    environment:
      #- DB_CONNECTION=mysql
      #- DB_HOST=project-db
      #- DB_DATABASE=${DB_NAME:-project_database}
      #- DB_USERNAME=${DB_USER:-project}
      #- DB_PASSWORD=${DB_PASS:-project123!db}
      - TZ=${TZ:-Asia/Tokyo}
    restart: always
    entrypoint: ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]

  web:
    image: nginx:1.19.10
    depends_on:
      - app
    container_name: project-web
    ports:
      - ${WEB_PORT:-8868}:8081
    volumes:
      - ./src:/work/app:delegated
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    environment:
      - TZ=${TZ:-Asia/Tokyo}
      - COMPOSE_PROJECT_NAME=app
    command: /bin/sh -c "envsubst '$$COMPOSE_PROJECT_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    restart: always





